package(default_visibility = [ "//visibility:public" ])
licenses(["notice"])

load(
  "@io_bazel_rules_rust//rust:rust.bzl",
  "rust_library",
)

rust_library(
  name = "unicode_bidi",
  srcs = glob(["lib.rs", "src/**/*.rs"]),
  deps = [
    "//matches-0.1.4:matches",
  ],
  rustc_flags = [
    "--cap-lints warn"
  ],
  crate_features = [ 
  ],
)
